# Generated by Django 4.0.3 on 2022-07-11 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('isbn', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField(default=0.0)),
                ('stock', models.IntegerField(default=0.0)),
                ('description', models.TextField()),
                ('Imageurl', models.URLField()),
                ('status', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tag', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0.0)),
                ('quantity', models.IntegerField(default=0.0)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('ImageURL', models.URLField()),
                ('status', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='commerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.CharField(max_length=50)),
                ('books', models.ManyToManyField(blank=True, max_length=100, to='commerce.book')),
                ('product', models.ManyToManyField(blank=True, max_length=100, to='commerce.product')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='commerce.category'),
        ),
    ]
